spring.application.name=risk-analytics-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/risk_analytics
spring.datasource.username=risk
spring.datasource.password=risk

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
